import { SITE_URL } from "@/lib/site";

export async function GET() {
  const body = [
    "Spirit Event Rentals",
    "",
    "Business summary:",
    "Local event rental provider offering tents, tables, chairs, and bundled packages for parties, weddings, showers, and backyard events.",
    "",
    "Geography served:",
    "Caldwell, NJ with surrounding towns across nearby counties.",
    "",
    "Booking workflow:",
    "1) Customer submits booking request",
    "2) Team reviews availability",
    "3) Rental agreement sent manually",
    "4) Stripe payment link sent manually",
    "",
    "Canonical URL:",
    `${SITE_URL}`,
    "",
    "Page map and intent:",
    `- ${SITE_URL}/`,
    "  Intent: local commercial discovery and conversion",
    "  Keywords: tent table chair rentals Caldwell NJ",
    "",
    `- ${SITE_URL}/packages`,
    "  Intent: transactional comparison",
    "  Keywords: event rental packages Caldwell NJ",
    "",
    `- ${SITE_URL}/gallery`,
    "  Intent: commercial investigation / proof",
    "  Keywords: event rental gallery Caldwell NJ",
    "",
    `- ${SITE_URL}/service-areas`,
    "  Intent: local coverage lookup",
    "  Keywords: event rentals near Caldwell NJ",
    "",
    `- ${SITE_URL}/booking-request`,
    "  Intent: conversion",
    "  Keywords: book event rentals Caldwell NJ",
    "",
    `- ${SITE_URL}/contact`,
    "  Intent: contact and qualification",
    "",
    `- ${SITE_URL}/faq`,
    "  Intent: objection handling and informational support",
    "",
    `- ${SITE_URL}/policy`,
    "  Intent: trust, terms, and planning details",
    "",
    "Internal conversion paths:",
    "Home -> Packages -> Booking Request",
    "Gallery -> Packages -> Booking Request",
    "Service Areas -> Town page -> Booking Request",
    "Policy/FAQ -> Booking Request",
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
    },
  });
}
